sonar.organization=optimuswave14
sonar.projectKey=optimuswave14_test-sonar-qube

# Path to the source directories (essential)
sonar.sources=.

# Use forward slashes even on Windows runners
sonar.sourceEncoding=UTF-8

# Host URL is required if not automatically picked up
sonar.host.url=https://sonarcloud.io
